### PR TITLE
String TLV Attribute max size should include length byte(s) (CON-1070)

### LINKED ISSUE #857: Bug causing emberAfExternalAttributeReadCallback to fail with string attributes
**Describe the bug**
The emberAfExternalAttributeReadCallback fails with the following log when creating string attributes (e.g. node label and device name):
```
I (13528) esp_matter_attribute: ********** R : Endpoint 0x0002's Cluster 0x00000039's Attribute 0x00000005 is Test Label **********
E (13542) esp_matter_attribute: Insufficient space for reading Endpoint 0x0002's Cluster 0x00000039's Attribute 0x00000005: required: 11, max: 10
```

The required size (11), returned by `get_data_from_attr_val` is the size of the full TLV UTF-8 string type value 
(data_size followed by the un-terminated string):
https://github.com/espressif/esp-matter/blob/release/v1.2/components/esp_matter/esp_matter_attribute_utils.cpp#L1253

The max size (10) is being set as the **string length only** and not the full TLV UTF-8 string type value:
https://github.com/espressif/esp-matter/blob/release/v1.2/components/esp_matter/esp_matter_core.cpp#L615

**Environment**
- ESP-Matter Commit Id: https://github.com/espressif/esp-matter/commit/0b515943fffd35243bc2d3d124e6dafdfae3cb11
- ESP-IDF Commit Id: https://github.com/espressif/esp-idf/commit/482a8fb2d78e3b58eb21b26da8a5bedf90623213
- SoC (eg: ESP32 or ESP32-C3): ESP32

### PR DESCRIPTION
**Pull request by JonathanWitthoeft**
Fixes #857

### CODE REVIEW

**Comment by shubhamdp** [comment]
@JonathanWitthoeft Thanks for the PR, we had identified this sometime back and wanted to fix it in a different way. We will push it out soon.

**Comment by JonathanWitthoeft** [comment]
@shubhamdp Any idea on a time frame? Will this fix be back-ported to release 1.2?

**Comment by shubhamdp** [comment]
> @shubhamdp Any idea on a time frame? Will this fix be back-ported to release 1.2?

Yes, this will be backported to v1.2 and v1.1 branches.

**Comment by shubhamdp** [comment]
@JonathanWitthoeft the fix is out, PTAL https://github.com/espressif/esp-matter/commit/d481fa9cf1d09001b1bbd9cd59dbb7836bbb13fe

**Comment by dhrishi** [comment]
@JonathanWitthoeft Fix for v1.2: 19f4775ff3cbf41305303f48114c1ee1410f3cbc. Closing this.

**Pull request closed without merging**
