### PR TITLE
add ws2812 led strip

### PR DESCRIPTION
**Pull request by Kristian8606**
Add ws2812 led strip for esp32

### CODE REVIEW

**Comment by chiragatal** [comment]
ws2812 driver is already supported for a single LED. It just needs to be extended for multiple LEDs. Ideally this should just require changes in the led_driver file. It should not require addition of another device and another example.

**Comment by Kristian8606** [comment]
> Драйверът ws2812 вече се поддържа за един светодиод. Просто трябва да се разшири за множество светодиоди. В идеалния случай това трябва просто да изисква промени във файла led_driver. Не трябва да изисква добавяне на друго устройство и друг пример.


I agree but when using esp32 and not esp32c then it loads gpio driver and not ws8212

**Comment by shubhamdp** [comment]
@Kristian8606 thank you for putting up a PR, Can you please update the description with what are you trying to suggest so that it would help review this PR.
Also, I see a lot of .DS_Store files can you please remove such unnecessary files.

**Comment by jonsmirl** [comment]
I also implement similar code.  The ESP library should handle strings and not just one LED.

**Comment by Kristian8606** [comment]
I will close this PR and open a new one

**Pull request closed without merging**
